/*法人テーブル*/
CREATE TABLE T_CORPORATE(
CORPORATE_ID VARCHAR2(12) PRIMARY KEY,
CORPORATE_NAME VARCHAR2(64),
KANA VARCHAR2(128),
DEPARTMENT_NAME VARCHAR2(32),
CONTACT_PERSON_NAME VARCHAR2(16),
POSTAL_CODE CHAR(7),
ADDRESS VARCHAR2(128),
TELEPHONE VARCHAR2(11),
EMAIL VARCHAR2(255),
PASSWORD VARCHAR2(64),
PAYDATE DATE,
DISCOUNT_RATE NUMBER(3),
CREDIT_LIMIT NUMBER,
START_DATE DATE,
FINISH_DATE DATE,
ACCOUNT NUMBER(3),
CREATED_AT TIMESTAMP
);
/*個人顧客テーブル*/
CREATE TABLE T_CUSTOMER(
CUSTOMER_ID VARCHAR2(12) PRIMARY KEY,
CUSTOMER_NAME VARCHAR2(32),
KANA VARCHAR2(64),
POSTAL_CODE CHAR(7),
ADDRESS VARCHAR2(128),
TELEPHONE VARCHAR2(11),
EMAIL VARCHAR2(255),
CREATED_AT TIMESTAMP
);
/*商品カテゴリーテーブル*/
CREATE TABLE T_CATEGORY(
CATEGORY_ID VARCHAR2(12) PRIMARY KEY,
CATEGORY_NAME VARCHAR2(16),
CREATED_AT TIMESTAMP
);
/*サプライヤーテーブル*/
CREATE TABLE T_SUPPLIER(
SUPPLIER_ID VARCHAR2(12) PRIMARY KEY,
SUPPLIER_NAME VARCHAR2(32),
KANA VARCHAR2(64),
POSTAL_CODE CHAR(7),
ADDRESS VARCHAR2(128),
TELEPHONE VARCHAR2(11),
EMAIL VARCHAR2(255),
CREATED_AT TIMESTAMP,
UPDATED_AT TIMESTAMP
);
/*商品テーブル*/
CREATE TABLE T_PRODUCT(
PRODUCT_ID VARCHAR2(12) PRIMARY KEY,
PRODUCT_NAME VARCHAR2(32),
KANA VARCHAR2(64),
PRICE NUMBER(8),
MANUFACTURER VARCHAR2(32),
ORDER_POINT NUMBER(3),
CREATED_AT TIMESTAMP,
UPDATED_AT TIMESTAMP,
STOP_FLG NUMBER(1),
CATEGORY_ID VARCHAR2(12) ,
FOREIGN KEY(CATEGORY_ID) REFERENCES T_CATEGORY(CATEGORY_ID)
);
/*注文テーブル*/
CREATE TABLE T_ORDER(
ORDER_ID VARCHAR2(12) PRIMARY KEY,
ORDER_DATE TIMESTAMP,
CORPORATE_ID VARCHAR2(12),
CUSTOMER_ID VARCHAR2(12),
FOREIGN KEY(CORPORATE_ID) REFERENCES T_CORPORATE(CORPORATE_ID),
FOREIGN KEY(CUSTOMER_ID) REFERENCES T_CUSTOMER(CUSTOMER_ID)
);
/*注文詳細テーブル*/
CREATE TABLE T_ORDER_DETAIL(
ORDER_DETAIL_ID VARCHAR2(12) PRIMARY KEY,
PRICE NUMBER(8),
NUM NUMBER(8),
ORDER_ID VARCHAR2(12),
PRODUCT_ID VARCHAR2(12) ,
FOREIGN KEY(ORDER_ID) REFERENCES T_ORDER(ORDER_ID),
FOREIGN KEY(PRODUCT_ID) REFERENCES T_PRODUCT(PRODUCT_ID)
);
/*見積テーブル*/
CREATE TABLE T_ESTIMATE(
ESTIMATE_ID VARCHAR2(12) PRIMARY KEY,
ESTIMATE_DATE TIMESTAMP,
CORPORATE_ID VARCHAR2(12),
FOREIGN KEY(CORPORATE_ID) REFERENCES T_CORPORATE(CORPORATE_ID)
);
/*見積詳細テーブル*/
CREATE TABLE T_ESTIMATE_DETAIL(
ESTIMATE_DETAIL_ID VARCHAR2(12) PRIMARY KEY,
NUM NUMBER(8),
PRICE NUMBER(8),
ESTIMATE_ID VARCHAR2(12),
PRODUCT_ID VARCHAR2(12),
FOREIGN KEY(ESTIMATE_ID) REFERENCES T_ESTIMATE(ESTIMATE_ID),
FOREIGN KEY(PRODUCT_ID) REFERENCES T_PRODUCT(PRODUCT_ID)
);
/*入金テーブル*/
CREATE TABLE T_PAYMENT(
PAYMENT_ID VARCHAR2(12) PRIMARY KEY,
PAYMENT_DATE DATE,
PAYMENT_FLG NUMBER(1),
REASON VARCHAR2(255),
ORDER_ID VARCHAR2(12),
FOREIGN KEY(ORDER_ID) REFERENCES T_ORDER(ORDER_ID)
);
/*配送業者テーブル*/
CREATE TABLE T_DELIVERY(
DELIVERY_ID VARCHAR2(12) PRIMARY KEY,
DELIVERY_NAME VARCHAR2(32),
KANA VARCHAR2(64),
CONTACT_PERSON VARCHAR2(16),
TELEPHONE VARCHAR(11),
EMAIL VARCHAR2(255),
POSTAL_CODE CHAR(7),
ADDRESS VARCHAR2(128),
CREATED_AT TIMESTAMP
);
/*配送テーブル*/
CREATE TABLE T_DELIVERY_DETAIL(
DELIVERY_DETAIL_ID VARCHAR2(12) PRIMARY KEY,
DELIVERY_DATE DATE,
DELIVERY_ID VARCHAR2(12),
FOREIGN KEY(DELIVERY_ID) REFERENCES T_DELIVERY(DELIVERY_ID)
);
/*発注テーブル*/
CREATE TABLE T_ORDERING(
ORDERING_ID VARCHAR2(12) PRIMARY KEY,
ORDERING_DATE TIMESTAMP,
DELIVERY_DATE DATE
);
/*発注詳細*/
CREATE TABLE T_ORDERING_DETAIL(
ORDERING_DETAIL_ID VARCHAR2(12) PRIMARY KEY,
ORDERING_ID VARCHAR2(12),
PRODUCT_ID VARCHAR2(12),
PRICE NUMBER(8),
NUM NUMBER(8),
DELIVERY_DATE DATE,
LACK_OR_EXCESS NUMBER(8),
FOREIGN KEY(ORDERING_ID) REFERENCES T_ORDER(ORDER_ID),
FOREIGN KEY(PRODUCT_ID) REFERENCES T_PRODUCT(PRODUCT_ID)
);
/*請求書ログテーブル*/
CREATE TABLE T_BILL(
BILL_ID VARCHAR2(12) PRIMARY KEY,
ORDER_ID VARCHAR2(12),
CREATED_AT TIMESTAMP,
UPDATED_AT TIMESTAMP,
NUM NUMBER(2),
FOREIGN KEY(ORDER_ID) REFERENCES T_ORDER(ORDER_ID)
);
/*在庫テーブル*/
CREATE TABLE T_STOCKS(
STOCK_ID VARCHAR2(12) PRIMARY KEY,
PRODUCT_ID VARCHAR2(12),
STOCK_NUM NUMBER(8),
PROVISION_NUM NUMBER(8),
UPDATED_AT TIMESTAMP,
FOREIGN KEY(PRODUCT_ID) REFERENCES T_PRODUCT(PRODUCT_ID)
);
/*サンプル商品在庫テーブル*/
CREATE TABLE T_SAMPLE(
SAMPLE_ID VARCHAR2(12) PRIMARY KEY,
PRODUCT_ID VARCHAR2(12),
STOCK_NUM NUMBER(3),
PROVISION_NUM NUMBER(3),
UPDATED_AT TIMESTAMP,
FOREIGN KEY(PRODUCT_ID) REFERENCES T_PRODUCT(PRODUCT_ID)
);
/*棚卸テーブル*/
CREATE TABLE T_INVENTORY(
INVENTORY_ID VARCHAR2(12) PRIMARY KEY,
PRODUCT_ID VARCHAR2(12),
NUM NUMBER(8),
LACK_OR_EXCESS NUMBER(8),
INVENTORY_DATE DATE,
FOREIGN KEY(PRODUCT_ID) REFERENCES T_PRODUCT(PRODUCT_ID)
);
/*商品破棄テーブル*/
CREATE TABLE T_ANNULMENT(
ANNULMENT_ID VARCHAR2(12) PRIMARY KEY,
PRODUCT_ID VARCHAR2(12),
NUM NUMBER(8),
REASON VARCHAR2(255),
CREATED_AT TIMESTAMP,
FOREIGN KEY(PRODUCT_ID) REFERENCES T_PRODUCT(PRODUCT_ID)
);
COMMIT;
